#!/usr/bin/env python3
"""Simulated PLC/RTU that publishes DDS samples of the PLC IDL module
(dds/idl/PlcValue.idl) for the scada_web web gateway to expose to web clients.

Purdue-model placement: this script *is* the Level 1 (PLC/RTU) boundary. It
owns the field-device scan loop and is the only thing in the sim that talks
DDS; Level 0 (the simulated process) lives in field_simulation.py and knows
nothing about DDS. The wire schema is the Python types generated by
rtiddsgen from dds/idl/PlcValue.idl (dds/gen/PlcValue.py, DD-052) -- the sim
imports and constructs them directly rather than building its own
DynamicData schema, so there is exactly one wire-type definition shared by
every component. Keeping the DDS entity/scan-loop concern (this file)
separate from the process-model concern (field_simulation.py) is still
deliberate, even in a small simulator, so the architecture doesn't imply
the field device, the network, and the data model are one undifferentiated
blob.

Publishing pattern, per the QoS-pattern comments already in the IDL:
  - MetaData: "Use State Data QoS pattern, only sent at startup, typically"
    -> published once per tag at startup, RELIABLE + TRANSIENT_LOCAL so a
       late-joining subscriber (e.g. scada_web itself, or a test client)
       still receives each tag's static description.
    - IdValue: "Use 1-many reliable QoS pattern ... reliability depends on
        whether all values update periodically or upon change"
        -> published periodically for every tag using the field-domain IdValue
             writer profile from dds/qos/profiles.xml.

Each tag publishes IdValue on its own schedule rather than a single shared
period: field_simulation.publish_period_s(uid) assigns uid 1-100 to 2 Hz,
101-200 to 1 Hz, 201-300 to every 5 s, and 301-500 to every 10 s. A min-heap
keyed on each tag's next-due time drives the scan loop so 500 independently
rated tags are serviced without polling every tag every tick.

Usage:
    python3 sim/plc_publisher.py --domain-id 15
"""

import argparse
import heapq
import logging
import logging.handlers
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(REPO_ROOT))

import rti.connextdds as dds

LOG_DIR = REPO_ROOT / "logs"
LOG_DIR.mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-5s %(name)s — %(message)s",
    datefmt="%H:%M:%S",
    handlers=[
        logging.StreamHandler(),
        logging.handlers.RotatingFileHandler(
            LOG_DIR / "sim.log",
            maxBytes=5 * 1024 * 1024,
            backupCount=3,
        ),
    ],
)
logger = logging.getLogger("scada_sim")

from field_simulation import PLC_HOSTNAME, Tag, build_tags, publish_period_s
from dds.gen.PlcValue import PLC

METADATA_TOPIC = "PLC::MetaDataTopic"
ID_VALUE_TOPIC = "PLC::IdValueTopic"

QOS_PROFILES_XML = str(Path(__file__).resolve().parent.parent / "dds" / "qos" / "profiles.xml")


def _now_ms() -> int:
    """valueTime convention used by this sim: milliseconds since Unix epoch."""
    return int(time.time() * 1000)


def _metadata_writer_qos() -> dds.DataWriterQos:
    provider = dds.QosProvider(QOS_PROFILES_XML)
    return provider.datawriter_qos_from_profile("field::metadata")


def _id_value_writer_qos() -> dds.DataWriterQos:
    provider = dds.QosProvider(QOS_PROFILES_XML)
    return provider.datawriter_qos_from_profile("field::idvalue")


def _value_t(value: float) -> "PLC.Value_t":
    """Builds a `PLC::Value_t` union sample selecting the KIND_FLOAT64 case.

    All simulated values in this module are engineering-unit floats, so this
    is the only case the sim needs to construct.
    """
    return PLC.Value_t(float64Value=value)


def _write_metadata(
    writer: dds.DataWriter, tag: Tag
) -> None:
    limits = tag.limits
    sample = PLC.MetaData(
        uid=tag.uid,
        valueTime=_now_ms(),
        hostname=PLC_HOSTNAME,
        longName=tag.long_name,
        limits=PLC.Limits_t(
            redHigh=_value_t(limits.red_high),
            redLow=_value_t(limits.red_low),
            yellowHigh=_value_t(limits.yellow_high),
            yellowLow=_value_t(limits.yellow_low),
            greenHigh=_value_t(limits.green_high),
            greenLow=_value_t(limits.green_low),
            active=limits.active,
        ),
    )
    writer.write(sample)


def _write_id_value(
    writer: dds.DataWriter,
    tag: Tag,
    t: float,
    previous_smoothed: float,
) -> float:
    raw = tag.raw_value(t)
    smoothed = tag.smoothed_value(t, raw, previous_smoothed)

    sample = PLC.IdValue(
        uid=tag.uid,
        valueTime=_now_ms(),
        smoothedValue=_value_t(smoothed),
        rawValue=_value_t(raw),
    )
    writer.write(sample)
    return smoothed


def run(domain_id: int, verbose: bool) -> None:
    tags = build_tags()
    tags_by_uid = {tag.uid: tag for tag in tags}

    participant = dds.DomainParticipant(domain_id)
    publisher = dds.Publisher(participant)

    metadata_topic = dds.Topic(participant, METADATA_TOPIC, PLC.MetaData)
    id_value_topic = dds.Topic(participant, ID_VALUE_TOPIC, PLC.IdValue)

    metadata_writer = dds.DataWriter(
        publisher, metadata_topic, _metadata_writer_qos()
    )
    id_value_writer = dds.DataWriter(
        publisher, id_value_topic, _id_value_writer_qos()
    )

    logger.info(
        "PLC sim '%s' publishing %d tags on domain %d: '%s' (once at startup) "
        "and '%s' (per-tag rate: uid 1-100 @ 2 Hz, 101-200 @ 1 Hz, "
        "201-300 every 5s, 301-500 every 10s).",
        PLC_HOSTNAME, len(tags), domain_id, METADATA_TOPIC, ID_VALUE_TOPIC,
    )

    for tag in tags:
        _write_metadata(metadata_writer, tag)
        if verbose:
            logger.debug("metadata: uid=%d name=%s", tag.uid, tag.name)

    smoothed_by_uid = {tag.uid: None for tag in tags}
    start = time.monotonic()

    # Min-heap of (next_due_time, uid, period_s); each entry is rescheduled
    # by period_s (not relative to `now`) on every publish, so a tag's cadence
    # does not drift from processing time spent on other tags.
    schedule: list = []
    for tag in tags:
        period = publish_period_s(tag.uid)
        heapq.heappush(schedule, (start + period, tag.uid, period))

    try:
        while True:
            due_time, uid, period = schedule[0]
            sleep_for = due_time - time.monotonic()
            if sleep_for > 0:
                time.sleep(sleep_for)
            heapq.heappop(schedule)

            tag = tags_by_uid[uid]
            t = time.monotonic() - start
            smoothed_by_uid[uid] = _write_id_value(
                id_value_writer, tag, t, smoothed_by_uid[uid]
            )
            if verbose:
                logger.debug(
                    "%s: raw=%.2f smoothed=%.2f %s",
                    tag.name, tag.raw_value(t), smoothed_by_uid[uid], tag.units,
                )

            heapq.heappush(schedule, (due_time + period, uid, period))
    except KeyboardInterrupt:
        logger.info("Stopping PLC sim.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--domain-id", type=int, default=15,
                        help="DDS domain ID (default: PLC::FIELD_DOMAIN_ID)")
    parser.add_argument(
        "--verbose", action="store_true", help="Print each sample as it's published"
    )
    args = parser.parse_args()
    run(args.domain_id, args.verbose)


if __name__ == "__main__":
    main()
