"""YAML configuration loader for scada_web.

Declares DDS participants, topic subscriptions, and QoS in a single YAML
file.

Types are Python classes generated by rtiddsgen from the IDL (DD-052, see
scada_web/gen/). Each topic entry specifies its type_name so the gateway can
create readers immediately at startup.

Config schema mirrors the pattern proven in act-sim-scope-infra's C++ router
(references/act-sim-scope-infra/router/config/) adapted for Python + the
presentation role (Role 2).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml


# ─── Data classes ────────────────────────────────────────────────────────────


@dataclass
class ParticipantConfig:
    """A DDS DomainParticipant declared in config."""
    name: str
    domain: int


@dataclass
class TopicConfig:
    """A topic to subscribe to. Type is a generated Python class (gen/)."""
    name: str
    participant: str  # references a ParticipantConfig.name
    type_name: str = ""  # fully-qualified IDL type, e.g. "PLC::MetaData"
    qos_profile: str | None = None


@dataclass
class WriterConfig:
    """A topic to publish."""
    name: str
    participant: str  # references a ParticipantConfig.name
    type_name: str = ""
    qos_profile: str | None = None



@dataclass
class ServerConfig:
    """Web server settings."""
    host: str = "0.0.0.0"
    port: int = 8080


@dataclass
class SelectionConfig:
    """Selection defaults for web-originated ValueRequest commands."""
    # Must be > 0 — see interest.py's _require_positive_separation for why.
    default_min_separation_ms: int = 250


@dataclass
class ScadaWebConfig:
    """Root configuration for scada_web."""
    qos_profiles: str = ""  # path to QoS profiles XML (dds/qos/profiles.xml)
    participants: list[ParticipantConfig] = field(default_factory=list)
    topics: list[TopicConfig] = field(default_factory=list)
    writers: list[WriterConfig] = field(default_factory=list)
    selection: SelectionConfig = field(default_factory=SelectionConfig)
    document_root: str = ""  # static dir to serve at "/", e.g. "UI"
    server: ServerConfig = field(default_factory=ServerConfig)

    # --- convenience lookups ---

    def topic_by_name(self, name: str) -> TopicConfig:
        for t in self.topics:
            if t.name == name:
                return t
        raise KeyError(f"no topic named '{name}'")


# ─── Loader ──────────────────────────────────────────────────────────────────


def load_config(path: str | Path) -> ScadaWebConfig:
    """Load and validate a scada_web YAML config file."""
    path = Path(path)
    with open(path) as f:
        raw = yaml.safe_load(f)

    cfg = ScadaWebConfig()

    # Participants
    for name, p in raw.get("participants", {}).items():
        cfg.participants.append(ParticipantConfig(
            name=name,
            domain=int(p["domain"]),
        ))

    # QoS profiles
    cfg.qos_profiles = raw.get("qos_profiles", "")

    # Topics
    for t in raw.get("topics", []):
        cfg.topics.append(TopicConfig(
            name=t["name"],
            participant=t["participant"],
            type_name=t.get("type", t["name"]),
            qos_profile=t.get("qos_profile"),
        ))

    # Writers
    for w in raw.get("writers", []):
        cfg.writers.append(WriterConfig(
            name=w["name"],
            participant=w["participant"],
            type_name=w.get("type", w["name"]),
            qos_profile=w.get("qos_profile"),
        ))

    # Selection defaults
    selection = raw.get("selection", {})
    cfg.selection = SelectionConfig(
        default_min_separation_ms=int(
            selection.get("default_min_separation_ms", 250)
        ),
    )

    # Static UI document root (served at "/")
    cfg.document_root = raw.get("document_root", "")

    # Server
    if "server" in raw:
        s = raw["server"]
        cfg.server = ServerConfig(
            host=s.get("host", "0.0.0.0"),
            port=int(s.get("port", 8080)),
        )

    _validate(cfg)
    return cfg


def _validate(cfg: ScadaWebConfig) -> None:
    """Cross-reference validation (participant refs exist, etc.)."""
    if cfg.selection.default_min_separation_ms <= 0:
        raise ValueError("selection.default_min_separation_ms must be > 0")
    if cfg.topics and not cfg.qos_profiles:
        raise ValueError("config must specify qos_profiles when topics are declared")
    participant_names = {p.name for p in cfg.participants}
    for t in cfg.topics:
        if t.participant not in participant_names:
            raise ValueError(
                f"topic '{t.name}' references unknown participant '{t.participant}'")
        if not t.qos_profile:
            raise ValueError(f"topic '{t.name}' must specify qos_profile")
    if cfg.writers and not cfg.qos_profiles:
        raise ValueError("config must specify qos_profiles when writers are declared")
    seen_writers: set[str] = set()
    for w in cfg.writers:
        if w.name in seen_writers:
            raise ValueError(f"duplicate writer '{w.name}'")
        seen_writers.add(w.name)
        if w.participant not in participant_names:
            raise ValueError(
                f"writer '{w.name}' references unknown participant "
                f"'{w.participant}'")
        if not w.qos_profile:
            raise ValueError(f"writer '{w.name}' must specify qos_profile")
