"""DDS gateway — manages participants, topics, and readers using generated types.

Orchestrates the lifecycle:
  1. Import Python generated types (from rtiddsgen -language python)
  2. Create DomainParticipants from config
  3. Create Topics + DataReaders immediately (types are known, no discovery wait)
  4. Create a DataWriter for ValueRequest (back-channel to selector)
  5. Forward received samples to the web layer via callbacks

This is the Level 2 (SCADA master) DDS boundary — it owns all DDS entities
and isolates the web server from DDS API details.

Types are Python dataclasses generated by rtiddsgen (DD-052). The data model
is commissioned SCADA infrastructure; it doesn't change at runtime.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from typing import Any, Callable

import rti.connextdds as dds
import rti.asyncio  # provides the WaitSet-backed asyncio dispatcher

from .config import ScadaWebConfig, TopicConfig, WriterConfig
from .gen.PlcValue import PLC

logger = logging.getLogger(__name__)

# Callback type: (topic_name, sample_data, sample_info) → None
SampleCallback = Callable[[str, Any, Any], None]

# Callback type: (topic_name, dds.PublicationMatchedStatus) → None
PublicationMatchedCallback = Callable[[str, Any], None]

# Map from IDL qualified type name → Python generated class
_TYPE_MAP: dict[str, type] = {
    "PLC::MetaData": PLC.MetaData,
    "PLC::IdValue": PLC.IdValue,
    "PLC::ValueRequest": PLC.ValueRequest,
}


@dataclass
class TopicRuntime:
    """Runtime state for a single subscribed topic."""
    config: TopicConfig
    topic: Any = None
    reader: Any = None


@dataclass
class WriterRuntime:
    """Runtime state for a single published topic."""
    config: WriterConfig
    topic: Any = None
    writer: Any = None
    # Kept alive here — the DDS binding does not hold its own reference, and a
    # garbage-collected listener silently stops firing.
    listener: Any = None


class _PublicationMatchedListener(dds.DataWriterListener):
    """Forwards on_publication_matched to the gateway's public callback.

    One instance per writer, closed over its own topic name so the gateway
    callback (server.py's SR-003 trigger, CR-003) doesn't need to inspect the
    writer to know which topic matched.
    """

    def __init__(self, gateway: "DdsGateway", topic_name: str):
        super().__init__()
        self._gateway = gateway
        self._topic_name = topic_name

    def on_publication_matched(self, writer: Any, status: Any) -> None:
        if self._gateway.on_publication_matched:
            self._gateway.on_publication_matched(self._topic_name, status)


class DdsGateway:
    """Manages DDS entities driven by YAML config and Python generated types.

    Lifecycle:
        gw = DdsGateway(config)
        gw.on_sample = my_callback
        await gw.start()   # creates participants + readers
        ...
        await gw.stop()    # tears down everything
    """

    def __init__(self, config: ScadaWebConfig):
        self._config = config
        self._participants: dict[str, dds.DomainParticipant] = {}
        self._qos_provider: dds.QosProvider | None = None
        self._topics: dict[str, TopicRuntime] = {}
        self._writers: dict[str, WriterRuntime] = {}
        self._reader_tasks: list[asyncio.Task] = []

        # Public callbacks — set before start()
        self.on_sample: SampleCallback | None = None
        # Fires on every writer's match-count change (SR-003 trigger, CR-003).
        # server.py filters by topic_name; a bare current_count_change > 0 with
        # current_count == current_count_change means the count just rose from
        # zero — the first moment a VOLATILE write to that topic can land.
        self.on_publication_matched: PublicationMatchedCallback | None = None

    # ─── Lifecycle ───────────────────────────────────────────────────────

    async def start(self) -> None:
        """Create participants, readers, and writers, then begin reading."""
        self._load_qos()
        self._create_participants()
        self._create_readers()
        self._create_writers()
        for topic_name, runtime in self._topics.items():
            task = asyncio.create_task(self._reader_loop(topic_name, runtime))
            self._reader_tasks.append(task)
        logger.info("dds_gateway_started participants=%d topics=%d writers=%d",
                    len(self._participants), len(self._topics),
                    len(self._writers))

    async def stop(self) -> None:
        """Tear down all DDS entities."""
        for task in self._reader_tasks:
            task.cancel()
        await asyncio.gather(*self._reader_tasks, return_exceptions=True)
        self._reader_tasks.clear()
        for dp in self._participants.values():
            dp.close()
        self._participants.clear()
        self._topics.clear()
        self._writers.clear()
        logger.info("dds_gateway_stopped")

    # ─── Internal: QoS loading ───────────────────────────────────────────

    def _load_qos(self) -> None:
        """Load QoS profiles XML."""
        if self._config.qos_profiles:
            self._qos_provider = dds.QosProvider(self._config.qos_profiles)
            logger.info("qos_profiles_loaded xml=%s", self._config.qos_profiles)

    def _resolve_type(self, type_name: str) -> type:
        """Resolve a config type_name to a Python generated type class."""
        cls = _TYPE_MAP.get(type_name)
        if cls is None:
            raise KeyError(f"unknown type '{type_name}' — add it to _TYPE_MAP")
        return cls

    # ─── Internal: participant + reader setup ────────────────────────────

    def _create_participants(self) -> None:
        for pc in self._config.participants:
            qos = dds.DomainParticipantQos()
            dp = dds.DomainParticipant(pc.domain, qos)
            self._participants[pc.name] = dp
            logger.info("participant_created name=%s domain=%d", pc.name, pc.domain)

    def _create_readers(self) -> None:
        """Create Topic + DataReader for each configured topic."""
        for tc in self._config.topics:
            dp = self._participants[tc.participant]
            type_cls = self._resolve_type(tc.type_name)

            topic = dds.Topic(dp, tc.name, type_cls)
            subscriber = dds.Subscriber(dp)

            if self._qos_provider is None:
                raise RuntimeError("qos_profiles must be loaded before creating readers")
            reader_qos = self._qos_provider.datareader_qos_from_profile(
                tc.qos_profile)
            logger.info("qos_applied topic=%s profile=%s", tc.name, tc.qos_profile)

            reader = dds.DataReader(subscriber, topic, reader_qos)
            self._topics[tc.name] = TopicRuntime(config=tc, topic=topic, reader=reader)
            logger.info("reader_created topic=%s type=%s", tc.name, type_cls.__name__)

    def _create_writers(self) -> None:
        """Create Topic + DataWriter for each configured published topic."""
        for wc in self._config.writers:
            dp = self._participants[wc.participant]
            type_cls = self._resolve_type(wc.type_name)

            # Reuse topic if a reader already created one with the same name
            existing = self._topics.get(wc.name)
            dds_topic = (existing.topic if existing is not None
                         else dds.Topic(dp, wc.name, type_cls))
            publisher = dds.Publisher(dp)

            if self._qos_provider is None:
                raise RuntimeError(
                    "qos_profiles must be loaded before creating writers")
            writer_qos = self._qos_provider.datawriter_qos_from_profile(
                wc.qos_profile)

            listener = _PublicationMatchedListener(self, wc.name)
            writer = dds.DataWriter(publisher, dds_topic, writer_qos,
                                     listener, dds.StatusMask.PUBLICATION_MATCHED)
            self._writers[wc.name] = WriterRuntime(
                config=wc, topic=dds_topic, writer=writer, listener=listener)
            logger.info("writer_created topic=%s type=%s profile=%s",
                        wc.name, type_cls.__name__, wc.qos_profile)

    # ─── Internal: read loop ─────────────────────────────────────────────

    async def _reader_loop(self, topic_name: str, runtime: TopicRuntime) -> None:
        """Async loop that reads new samples and forwards via callback."""
        reader = runtime.reader
        if reader is None:
            return
        condition = dds.ReadCondition(reader, dds.DataState.new_data)
        dispatcher = rti.asyncio._get_default_dispatcher()
        with dispatcher.register(condition) as wait_token:
            try:
                await dispatcher.wait(wait_token)
                while True:
                    for data, info in reader.select().state(
                            dds.DataState.new_data).read():
                        if not info.valid:
                            continue
                        if self.on_sample:
                            self.on_sample(topic_name, data, info)
                    await dispatcher.wait(wait_token)
            except asyncio.CancelledError:
                dispatcher.waitset.detach_condition(wait_token.condition)
                raise
            except Exception:
                logger.exception("reader_loop_error topic=%s", topic_name)

    # ─── Public query ────────────────────────────────────────────────────

    @property
    def topics(self) -> list[str]:
        """All configured topic names."""
        return list(self._topics.keys())

    def read_samples(self, topic_name: str) -> list[tuple[Any, Any]]:
        """Every retained sample for a topic, regardless of sample state."""
        runtime = self._topics[topic_name]
        reader = runtime.reader
        if reader is None:
            return []
        return [(data, info)
                for data, info in reader.select().state(dds.DataState.any).read()
                if info.valid]

    def write(self, topic_name: str, sample: Any) -> None:
        """Write a typed sample to the named topic."""
        runtime = self._writers[topic_name]
        writer = runtime.writer
        if writer is None:
            raise KeyError(f"no writer for topic '{topic_name}'")
        writer.write(sample)

    def read_sample(self, topic_name: str, uid: int | None = None) -> tuple[Any, Any] | None:
        """Read one current sample without removing it from DDS cache."""
        for data, info in self.read_samples(topic_name):
            if uid is None:
                return data, info
            try:
                if data.uid == uid:
                    return data, info
            except Exception:
                continue
        return None
